services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"
    depends_on:
      - nginx-exporter
      - f2b-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "13000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./dashboards:/etc/grafana/dashboards
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Change this in production!
    depends_on:
      - prometheus

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    ports: 
      - "9113:9113"
    command:
      - '--nginx.scrape-uri=http://172.26.0.1/nginx_status'

  f2b-exporter:
    image: registry.gitlab.com/hctrdev/fail2ban-prometheus-exporter:latest
    container_name: f2b-exporter
    volumes:
      - /var/run/fail2ban/:/var/run/fail2ban:ro
    ports:
      - "9191:9191"

volumes:
  grafana-data:

networks:
  default:
    driver: bridge
