global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113'] 
  - job_name: 'f2b'
    static_configs:
      - targets: ['f2b-exporter:9191']
