services:
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    command:
      - '--nginx.scrape-uri=http://172.17.0.1:80/nginx_status'
    network_mode: "host"